### ISSUE TITLE
Vue or Vue2?

### ISSUE THREAD

**Issue by jujes** [NdagiStanley/vue-django#12]
Hi, this project is based on vue or vue2?

thanks in advance,

**Comment by jakub-wisniewski** [comment]
vue2

2017-09-18 21:19 GMT+02:00 jujes <notifications@github.com>:

**Comment by lben** [comment]
I am sorry for reopening this but using this template I have Vue 1.0.28. I am having some problems with another dependencies because they need Vue 2. The vue chrome plugin detectes Vue 1.0.28 as well as npm-update. Am I doing something wrong? or is this template still using Vue 1? Thank you!

**Comment by NdagiStanley** [comment]
Hey Iben. I'll be looking into this tomorrow.

**Comment by holic-cl** [comment]
Same problem here. Any update?.

**Comment by philipithomas** [comment]
Same problem - on Vue 1.0.28

**Comment by NdagiStanley** [comment]
Noted the issue as @Iben explained.

Here's the screenshot from the Vue dev tools:
<img width="341" alt="screenshot 2017-11-20 22 51 07" src="https://user-images.githubusercontent.com/15629602/33072962-6d623962-ced2-11e7-9f6c-52e5d8f0cfe4.png">

Moving forward we'll use: `vue init NdagiStanley/vue-django#1.0 my-project` for Vuejs version 1.x.

I'm working on VueJS version 2 so that it is the default and initialised by running: `vue init NdagiStanley/vue-django my-project`

**Comment by rambii** [comment]
@NdagiStanley The command `vue init NdagiStanley/vue-django my-project` was still initialising with Vue 1.

I had to run `vue init NdagiStanley/vue-django#develop my-project` to init with Vue 2.

Should the merge be made to the master branch instead of develop or is this still WIP?

I also had problems installing django with the develop branch since django 2 only supports python3 which is not taken care of in the Dockerfile.
I opened a new issue for that matter #74.
